import { Entity, type EntityData } from '@engine/world';
import type { Scene } from '@engine/world';

export class Clipboard {
  private data: EntityData[] = [];

  copy(entities: Entity[]): void {
    // Deep clone serialized entities to avoid retaining references to source data
    this.data = entities.map((e) => {
      const json = e.toJSON();
      const structured = (globalThis as unknown as {
        structuredClone?: <T>(value: T) => T;
      }).structuredClone;
      if (typeof structured === 'function') {
        return structured<EntityData>(json);
      }
      // Fallback: JSON clone (typed arrays will degrade to plain arrays)
      return JSON.parse(JSON.stringify(json)) as EntityData;
    });
  }

  paste(targetScene: Scene): Entity[] {
    const created: Entity[] = [];
    for (const data of this.data) {
      const entity = Entity.fromJSON(data);
      // New IDs are generated by fromJSON; attach as root
      targetScene.addEntity(entity);
      created.push(entity);
    }
    return created;
  }
}
