/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_packresult_free: (a: number, b: number) => void;
export const __wbg_pbrresult_free: (a: number, b: number) => void;
export const build_atlas: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const build_atlas_with_padding: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const calculate_mip_count: (a: number, b: number) => number;
export const generate_ao_map: (a: number, b: number, c: any, d: number, e: number, f: number, g: number) => void;
export const generate_emission_map: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const generate_flat_normal_map: (a: number, b: number, c: any, d: number, e: number) => void;
export const generate_metallic_map: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number) => void;
export const generate_mipmaps_box: (a: number, b: number, c: number, d: number) => [number, number];
export const generate_mipmaps_lanczos: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const generate_no_emission: (a: number, b: number, c: any, d: number, e: number) => void;
export const generate_normal_map: (a: number, b: number, c: number, d: number, e: any, f: number, g: number, h: number) => void;
export const generate_pbr_texture: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const generate_roughness_map: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const generate_uniform_roughness: (a: number, b: number, c: any, d: number, e: number, f: number) => void;
export const get_mip_info: (a: number, b: number, c: number) => [number, number];
export const pack_rectangles: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const packresult_atlas_height: (a: number) => number;
export const packresult_atlas_width: (a: number) => number;
export const packresult_packed_count: (a: number) => number;
export const packresult_positions: (a: number) => [number, number];
export const pbrresult_albedo: (a: number) => [number, number];
export const pbrresult_ao: (a: number) => [number, number];
export const pbrresult_emission: (a: number) => [number, number];
export const pbrresult_height: (a: number) => number;
export const pbrresult_metallic: (a: number) => [number, number];
export const pbrresult_normal: (a: number) => [number, number];
export const pbrresult_roughness: (a: number) => [number, number];
export const pbrresult_width: (a: number) => number;
export const perlin_2d: (a: number, b: number, c: number) => number;
export const perlin_2d_batch: (a: number, b: number, c: any, d: number, e: number, f: number, g: number) => void;
export const perlin_fbm: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const simplex_2d: (a: number, b: number, c: number) => number;
export const simplex_2d_batch: (a: number, b: number, c: any, d: number, e: number, f: number, g: number) => void;
export const simplex_fbm: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const worley_2d_batch: (a: number, b: number, c: any, d: number, e: number, f: number, g: number) => void;
export const worley_f1f2: (a: number, b: number, c: number) => number;
export const worley_inverted: (a: number, b: number, c: number) => number;
export const worley_2d: (a: number, b: number, c: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
