/**
 * WASM Texture Processor
 *
 * High-performance texture generation using Rust/WASM with SIMD support.
 * Provides procedural noise, PBR map generation, mipmaps, and atlas packing.
 *
 * @example
 * ```typescript
 * import { WasmTextureProcessor } from '@engine/wasm-texture-processor';
 *
 * await WasmTextureProcessor.initialize();
 *
 * const pbr = WasmTextureProcessor.generatePBRTexture(128, 128, {
 *   pattern: 'noise',
 *   color: [0.5, 0.5, 0.5, 1.0],
 *   roughness: 0.5,
 *   metallic: 0.0,
 * });
 * ```
 */

// Types for WASM module (will be generated by wasm-bindgen)
interface TextureProcessorWasm {
  init_panic_hook?: () => void;
  perlin_2d: (x: number, y: number, seed: number) => number;
  perlin_2d_batch: (output: Float32Array, width: number, height: number, scale: number, seed: number) => void;
  simplex_2d: (x: number, y: number, seed: number) => number;
  simplex_2d_batch: (output: Float32Array, width: number, height: number, scale: number, seed: number) => void;
  worley_2d: (x: number, y: number, seed: number) => number;
  worley_2d_batch: (output: Float32Array, width: number, height: number, scale: number, seed: number) => void;
  generate_pbr_texture: (
    width: number,
    height: number,
    pattern: number,
    color: Float32Array,
    params: Float32Array,
    seed: number
  ) => PBRResultWasm;
  generate_normal_map: (
    heightData: Float32Array,
    output: Uint8Array,
    width: number,
    height: number,
    strength: number
  ) => void;
  generate_mipmaps_box: (baseData: Uint8Array, width: number, height: number) => Uint8Array;
  generate_mipmaps_lanczos: (baseData: Uint8Array, width: number, height: number, radius: number) => Uint8Array;
  calculate_mip_count: (width: number, height: number) => number;
  get_mip_info: (baseWidth: number, baseHeight: number, level: number) => Uint32Array;
  pack_rectangles: (widths: Uint32Array, heights: Uint32Array, maxAtlasSize: number, padding: number) => PackResultWasm;
  build_atlas: (
    textures: Uint8Array,
    texSizes: Uint32Array,
    atlasWidth: number,
    atlasHeight: number,
    positions: Uint32Array
  ) => Uint8Array;
}

interface PBRResultWasm {
  albedo: () => Uint8Array;
  normal: () => Uint8Array;
  roughness: () => Uint8Array;
  metallic: () => Uint8Array;
  ao: () => Uint8Array;
  emission: () => Uint8Array;
  width: () => number;
  height: () => number;
  free: () => void;
}

interface PackResultWasm {
  positions: () => Uint32Array;
  atlas_width: () => number;
  atlas_height: () => number;
  packed_count: () => number;
  free: () => void;
}

// TypeScript types

export type NoiseType = 'perlin' | 'simplex' | 'worley';

export type PatternType = 'solid' | 'smooth' | 'noise' | 'cobble' | 'bricks' | 'planks' | 'grid';

export interface PBRTextureOptions {
  pattern: PatternType;
  color: [number, number, number, number]; // RGBA 0-1
  roughness?: number;
  metallic?: number;
  emissionColor?: [number, number, number];
  emissionIntensity?: number;
  seed?: number;
}

export interface PBRTextureData {
  albedo: Uint8Array;
  normal: Uint8Array;
  roughness: Uint8Array;
  metallic: Uint8Array;
  ao: Uint8Array;
  emission: Uint8Array;
  width: number;
  height: number;
}

export interface MipmapOptions {
  filter?: 'box' | 'lanczos';
  lanczosRadius?: number;
}

export interface AtlasPackResult {
  positions: Uint32Array;
  atlasWidth: number;
  atlasHeight: number;
  packedCount: number;
}

export interface TextureRect {
  width: number;
  height: number;
  data: Uint8Array;
}

// Pattern type to number mapping
const PATTERN_MAP: Record<PatternType, number> = {
  solid: 0,
  smooth: 1,
  noise: 2,
  cobble: 3,
  bricks: 4,
  planks: 5,
  grid: 6,
};

/**
 * WASM Texture Processor
 *
 * Static class providing high-performance texture generation.
 */
export class WasmTextureProcessor {
  private static wasm: TextureProcessorWasm | null = null;
  private static initPromise: Promise<void> | null = null;

  /**
   * Initialize the WASM module
   *
   * Must be called before using any other methods.
   * Safe to call multiple times (will only initialize once).
   */
  static async initialize(): Promise<void> {
    if (this.wasm) return;

    if (this.initPromise) {
      return this.initPromise;
    }

    this.initPromise = this.doInitialize();
    return this.initPromise;
  }

  private static async doInitialize(): Promise<void> {
    try {
      // Dynamic import of WASM module
      const wasmModule = await import('../pkg/texture_processor.js');
      await wasmModule.default();
      this.wasm = wasmModule as unknown as TextureProcessorWasm;

      // Initialize panic hook for better error messages
      if (this.wasm.init_panic_hook) {
        this.wasm.init_panic_hook();
      }

      console.info('[WasmTextureProcessor] Initialized successfully');
    } catch (error) {
      console.warn('[WasmTextureProcessor] Failed to initialize:', error);
      this.wasm = null;
      throw error;
    }
  }

  /**
   * Check if WASM module is available
   */
  static isAvailable(): boolean {
    return this.wasm !== null;
  }

  /**
   * Generate noise texture
   *
   * @param type - Noise type ('perlin', 'simplex', 'worley')
   * @param width - Texture width
   * @param height - Texture height
   * @param scale - Noise scale (smaller = larger features)
   * @param seed - Random seed
   * @returns Float32Array with noise values [-1, 1] for Perlin/Simplex, [0, 1] for Worley
   */
  static generateNoise(
    type: NoiseType,
    width: number,
    height: number,
    scale: number = 0.1,
    seed: number = 12345
  ): Float32Array {
    this.ensureInitialized();

    const output = new Float32Array(width * height);

    switch (type) {
      case 'perlin':
        this.wasm!.perlin_2d_batch(output, width, height, scale, seed);
        break;
      case 'simplex':
        this.wasm!.simplex_2d_batch(output, width, height, scale, seed);
        break;
      case 'worley':
        this.wasm!.worley_2d_batch(output, width, height, scale, seed);
        break;
    }

    return output;
  }

  /**
   * Generate complete PBR texture set
   *
   * @param width - Texture width
   * @param height - Texture height
   * @param options - PBR generation options
   * @returns All PBR texture maps
   */
  static generatePBRTexture(width: number, height: number, options: PBRTextureOptions): PBRTextureData {
    this.ensureInitialized();

    const color = new Float32Array(options.color);
    const params = new Float32Array([
      options.roughness ?? 0.5,
      options.metallic ?? 0.0,
      options.emissionColor?.[0] ?? 0.0,
      options.emissionColor?.[1] ?? 0.0,
      options.emissionColor?.[2] ?? 0.0,
      options.emissionIntensity ?? 0.0,
    ]);

    const patternId = PATTERN_MAP[options.pattern] ?? 0;
    const seed = options.seed ?? Math.floor(Math.random() * 1000000);

    const result = this.wasm!.generate_pbr_texture(width, height, patternId, color, params, seed);

    const data: PBRTextureData = {
      albedo: result.albedo(),
      normal: result.normal(),
      roughness: result.roughness(),
      metallic: result.metallic(),
      ao: result.ao(),
      emission: result.emission(),
      width: result.width(),
      height: result.height(),
    };

    result.free();
    return data;
  }

  /**
   * Generate normal map from height data
   *
   * @param heightData - Height map (width * height floats, 0-1 range)
   * @param width - Texture width
   * @param height - Texture height
   * @param strength - Normal intensity (1.0 = subtle, 3.0+ = strong)
   * @returns RGBA normal map
   */
  static generateNormalMap(heightData: Float32Array, width: number, height: number, strength: number = 2.0): Uint8Array {
    this.ensureInitialized();

    const output = new Uint8Array(width * height * 4);
    this.wasm!.generate_normal_map(heightData, output, width, height, strength);
    return output;
  }

  /**
   * Generate mipmap chain
   *
   * @param baseData - Base level RGBA data
   * @param width - Base level width
   * @param height - Base level height
   * @param options - Mipmap options
   * @returns All mipmap levels concatenated
   */
  static generateMipmaps(baseData: Uint8Array, width: number, height: number, options?: MipmapOptions): Uint8Array {
    this.ensureInitialized();

    const filter = options?.filter ?? 'box';

    if (filter === 'lanczos') {
      const radius = options?.lanczosRadius ?? 2;
      return this.wasm!.generate_mipmaps_lanczos(baseData, width, height, radius);
    }

    return this.wasm!.generate_mipmaps_box(baseData, width, height);
  }

  /**
   * Get mipmap level count for given dimensions
   */
  static getMipCount(width: number, height: number): number {
    this.ensureInitialized();
    return this.wasm!.calculate_mip_count(width, height);
  }

  /**
   * Get offset and size for specific mip level
   *
   * @returns [offset, width, height]
   */
  static getMipInfo(baseWidth: number, baseHeight: number, level: number): [number, number, number] {
    this.ensureInitialized();
    const info = this.wasm!.get_mip_info(baseWidth, baseHeight, level);
    return [info[0], info[1], info[2]];
  }

  /**
   * Pack rectangles into atlas
   *
   * @param textures - Array of textures with width/height
   * @param maxAtlasSize - Maximum atlas dimension
   * @param padding - Padding between textures
   * @returns Packing result with positions
   */
  static packRectangles(
    textures: Array<{ width: number; height: number }>,
    maxAtlasSize: number = 2048,
    padding: number = 2
  ): AtlasPackResult {
    this.ensureInitialized();

    const widths = new Uint32Array(textures.map((t) => t.width));
    const heights = new Uint32Array(textures.map((t) => t.height));

    const result = this.wasm!.pack_rectangles(widths, heights, maxAtlasSize, padding);

    const packResult: AtlasPackResult = {
      positions: result.positions(),
      atlasWidth: result.atlas_width(),
      atlasHeight: result.atlas_height(),
      packedCount: result.packed_count(),
    };

    result.free();
    return packResult;
  }

  /**
   * Build atlas texture from packed textures
   *
   * @param textures - Array of textures with data
   * @param positions - Positions from packRectangles
   * @param atlasWidth - Atlas width
   * @param atlasHeight - Atlas height
   * @returns Atlas RGBA data
   */
  static buildAtlas(textures: TextureRect[], positions: Uint32Array, atlasWidth: number, atlasHeight: number): Uint8Array {
    this.ensureInitialized();

    // Concatenate all texture data
    const totalBytes = textures.reduce((sum, t) => sum + t.data.length, 0);
    const concatenated = new Uint8Array(totalBytes);
    let offset = 0;

    const sizes: number[] = [];
    for (const tex of textures) {
      concatenated.set(tex.data, offset);
      offset += tex.data.length;
      sizes.push(tex.width, tex.height);
    }

    const texSizes = new Uint32Array(sizes);

    return this.wasm!.build_atlas(concatenated, texSizes, atlasWidth, atlasHeight, positions);
  }

  /**
   * Ensure WASM is initialized, throw if not
   */
  private static ensureInitialized(): void {
    if (!this.wasm) {
      throw new Error('[WasmTextureProcessor] Not initialized. Call initialize() first.');
    }
  }
}

// Re-export types
export type { TextureProcessorWasm, PBRResultWasm, PackResultWasm };

